<?php 
use Zend\Permissions\Acl\Acl;  
use Zend\Permissions\Acl\Role\GenericRole as Role; 
use Zend\Permissions\Acl\Resource\GenericResource as Resource;   

if ($userr = $this->identity())  {
	echo '<h2> Welcome '.$userr->name. '</h2>';  
	
	
}


if (isset($this->message) ) {

	echo '<h2>'.$this->message. '</h2>';  
	
}


if (isset($this->error) ) {

	echo '<h2>'.$this->error. '</h2>';  
	
}



if (isset ($this->user))  { 
	echo '<h2> welcome '.$this->escapeHtml($this->user->name).'</h2>';
	
	$logout = $this->url('logout-route'); 
	

?>

		<a href="<?php echo $logout;?>">Logout </a> 
<?php
		
}


$form=$this->form;
 
if (isset($form)) {
	
	$form->prepare();


	$form->setAttribute('action', $this->url('login-form'));


	// Set the method attribute for the form
	$form->setAttribute('method', 'post');

	// Get the form label plugin
	$formLabel = $this->plugin('formLabel');

	// Render the opening tag

	echo $this->form()->openTag($form); 
	?>  


	<div class="form_element">
	<?php 
		$name=$form->get('username');  
		echo $this->formRow($name);
		
	   // $name = $form->get('name');
	//echo $formLabel->openTag() . $name->getOption('label');
		//echo $this->formInput($name);
		//echo $this->formElementErrors($name);
		//echo $formLabel->closeTag();
	?></div>



	<div class="form_element">
	<?php 
		$password = $form->get('password');
		echo $formLabel->openTag() . $password->getOption('label');
		echo $this->formInput($password);
		echo $this->formElementErrors($password);
		echo $formLabel->closeTag();
	?></div>



	<?= $this->formElement($form->get('send')) ?>

	<?= $this->form()->closeTag() ?>
	
		
<?php
	
	
}
		

	
?>  


	
	
	