<?php 
	$form=$this->addDriverForm;  

	$title='Add new driver';
	
	$this->headTitle($title);  
?>

	<h2><?= $this->escapeHtml($title) ?> </h2> 
	
<?php 
	
	$name=$form->get('name');  
	
	$name->setAttribute ('class','form-control');
//	$name->setAttribute('placeholder', 'driver\'s name');  
	
	$age=$form->get('age');
	$age->setAttribute ('class','form-control');
	$age->setAttribute('placeholder', 21);  
	
	$category=$form->get('category');  
	
	$category->setAttribute ('class','form-control');
	$category->setAttribute('placeholder', 'driver\'s category');  
	

	
	$csrf=  $form ->get('csrf');  
	
	
	
	
	
	$submit = $form->get('submit');
	$submit->setAttribute('class', 'btn btn-primary');
	
	$form->setAttribute('action', $this->url('driver', ['action' => 'add']));
	$form->prepare();
?>
	
	<?= $this->form()->openTag($form); ?>

	<div class="form-group">
		<?= $this->formLabel($name) ?>
		<?= $this->formElement($name) ?>
		<?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
	</div>

	<div class="form-group">
		<?= $this->formLabel($age) ?>
		<?= $this->formElement($age) ?>
		<?= $this->formElementErrors()->render($age, ['class' => 'help-block']) ?>
	</div>
	
	<div class="form-group">
		<?= $this->formLabel($category) ?>
		<?= $this->formElement($category) ?>
		<?= $this->formElementErrors()->render($category, ['class' => 'help-block']) ?>
	</div>
	
	<div class="form-group">
		
		<?= $this->formElement($csrf) ?>
		<?= $this->formElementErrors()->render($csrf, ['class' => 'help-block']) ?>
	</div>

	<?php
	echo $this->formSubmit($submit);

	echo $this->form()->closeTag();
	
?> 
	

	
		