


<?php if ( $this->pageCount ) : ?>
<div> 

	<ul class="pagination">   
	
<?php	if (isset($this->previous)):  ?>
	<li>
		<a href="<?php echo $this->url ('album-page', ['page'=>$this->previous]); ?>">&lt;&lt;</a>
	</li>


<?php else:  ?>
	<li class="disabled"><a>&lt;&lt;</a></li>
	
<?php endif;  ?>  

	<?php  foreach ($this->pagesInRange as $page)  : ?> 
			<?php if ($page!= $this->current):  ?> 

	<li>
	
		<a href="<?php echo $this->url('album-page', ['page'=>$page]);?>"><?=$page ?></a>
	</li>  
	
	<?php  else: ?> 
	
	<li class="disabled"><a><?= $page?> </a></li>
	<?php  endif;  ?> 
	
	
	<?php endforeach;  ?> 
	
	
	
	<?php if (isset($this->next)):  ?>
	<li> 
		<a href="<?php echo $this->url ('album-page', ['page'=>$this->next]); ?>">&gt;&gt;</a>
	</li>  


<?php else:  echo "<li class='disabled'><a>&gt;&gt;</a></li>";  endif;  ?> 
	
	</ul> 

</div> 

<?php endif; ?> 
	
	
	
