<?php 
   
	// module/Album/view/album/album/edit.phtml:

	$title = 'Edit album';
	$this->headTitle($title);
	$idd=$this->form->getObject()->id; 
	?>
	<h1><?= $this->escapeHtml($title) ?></h1>
	<?php
	$id = $form->get('id');
	$id->setAttribute('class', 'form-control');
	$id->setAttribute('value', $this->form->getObject()->id);

	
	
	$title = $form->get('title');
	$title->setAttribute('class', 'form-control');
	$title->setAttribute('value', $this->form->getObject()->title);

	$artist = $form->get('artist');
	$artist->setAttribute('class', 'form-control');
	$artist->setAttribute('value', $this->form->getObject()->artist);

	$submit = $form->get('submit');
	$submit->setAttribute('class', 'btn btn-primary');

	$form->setAttribute('action', $this->url('album', [
		'action' => 'edit',
		'id'     => $idd,
	]));
	$form->prepare();

	echo $this->form()->openTag($form);
	?>
	<div class="form-group">
	
		<?= $this->formElement($id) ?>
		
	</div>
	
	
	<div class="form-group">
		<?= $this->formLabel($title) ?>
		<?= $this->formElement($title) ?>
		<?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
	</div>

	<div class="form-group">
		<?= $this->formLabel($artist) ?>
		<?= $this->formElement($artist) ?>
		<?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
	</div>

	<?php
	echo $this->formSubmit($submit);
	echo $this->formHidden($form->get('id'));
	echo $this->form()->closeTag();