<?php  

use Zend\Paginator\Paginator;
use Zend\View\Helper\PaginationControl;

$title = 'My albums';

$this->headTitle($title);   
$drivers=$this->url('driver');

$user=$this->user;

$acl= $this->acl; 

isset ($this->paginator) ? $albums=$this->paginator : $albums=$this->albums;  


?>
<h3><a href="<?= $drivers ;?>">Go to drivers</a></h3> 

<h3><a href="<?= $this->url('login-form') ;?>">Go to main page</a></h3> 


<h2><?= $this->escapeHtml($title) ?></h2>


<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : 
   $album->user =unserialize ($album->user); 


?>
    <tr>
        <td><?= $this->escapeHtml($album->title) ?></td>
        <td><?= $this->escapeHtml($album->artist) ?></td>
        <td>
            <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
		</td> 
		<td> 
			<?php 
			
			if ( $acl->isAllowed( $user, $album , 'delete')) { ?>
			
			<a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
			
			<?php 
			}
			else {
				
				echo 'Delete';  
			}
			
			
			?>
			
        </td>
		<td>
			
		
		
		</td> 
		
	
		
    </tr>
	
<?php endforeach; ?>
</table>

<?php 



	echo $this->paginationControl (
		$albums, 
		'Sliding', 
		'partials/paginator',
		[
			'route'=>'album-page', 
		
		]
	
	);
	
	
	