<?php  






$title = 'My albums';
$this->headTitle($title);
$user=$this->user;  
$logout= $this->url('logout-route');  
?>

<h1><?= 'Hello, '.$this->escapeHtml($user) ?>&nbsp;&nbsp;<a href="<?= $logout; ?>">Logout</a></h1>


<h2><?= $this->escapeHtml($title) ?></h2>


<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
    <tr>
        <td><?= $this->escapeHtml($album->title) ?></td>
        <td><?= $this->escapeHtml($album->artist) ?></td>
        <td>
            <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
            <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>

