<?php 

	$drivers=$this->drivers;
?>

<!doctype=html>
<html>
	<head>
		<style>
			table, table * {
				border:1px solid black;  
				padding:10px;  
				text-align:center;  
			}
		
		
		</style>  
	
	
	</head>
	<body> 
		<p>
	
			<a href="<?= $this->url('album', ['action' => 'add']); ?>">Add driver</a>
		</p> 
		<table style="border:1px solid black;">
			<tr>
				<th>Name</th> 
				<th>Age</th> 
				<th>Cat</th> 
				<th>Edit</th> 
				<th>Delete</th>
			
			</tr>
		

	<?php foreach ($drivers as $driver) : ?>
		<tr>
			<td><?= $this->escapeHtml($driver->name) ?></td>
			<td><?= $this->escapeHtml($driver->age) ?></td>
			<td><?= $this->escapeHtml($driver->category) ?></td>
			<td>
				<a href="<?= $this->url('acl', ['action' => 'edit', 'id' => $driver->id_driver]) ?>">Edit</a>
			</td> 
			<td> 
				<a href="<?= $this->url('acl', ['action' => 'delete', 'id' => $driver->id_driver]) ?>">Delete</a>
			</td>
		</tr>
	<?php endforeach; ?>
		</table>


	
		
	</body>
	
</html> 